/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Modelo.*;
import control.*;
import javax.swing.table.DefaultTableModel;
import Datos.*;
/**
 *
 * @author Alexander Cruz
 */
public class IUPrincipal extends javax.swing.JFrame {

    private GestorUsuario gestorUsuario;
    
    public IUPrincipal() {
        initComponents();
        this.gestorUsuario = new GestorUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuVerificarUsuario = new javax.swing.JMenuItem();
        jVerificarAsesor = new javax.swing.JMenuItem();
        jVerificarTecnico = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuInfoSistema = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem4.setText("jMenuItem4");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu8.setText("jMenu8");

        jMenu7.setText("File");
        jMenuBar4.add(jMenu7);

        jMenu9.setText("Edit");
        jMenuBar4.add(jMenu9);

        jMenu10.setText("File");
        jMenuBar5.add(jMenu10);

        jMenu11.setText("Edit");
        jMenuBar5.add(jMenu11);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/comdataGroup.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 430));

        jMenuBar1.setBackground(new java.awt.Color(101, 132, 255));

        jMenu1.setBackground(new java.awt.Color(101, 132, 255));
        jMenu1.setText("Menú");
        jMenu1.setToolTipText("");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jMenu1.setOpaque(true);

        jMenuVerificarUsuario.setBackground(new java.awt.Color(188, 202, 236));
        jMenuVerificarUsuario.setText("Verificar Usuario");
        jMenuVerificarUsuario.setOpaque(true);
        jMenuVerificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVerificarUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuVerificarUsuario);

        jVerificarAsesor.setBackground(new java.awt.Color(188, 202, 236));
        jVerificarAsesor.setText("Verificar Asesor");
        jVerificarAsesor.setOpaque(true);
        jVerificarAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVerificarAsesorActionPerformed(evt);
            }
        });
        jMenu1.add(jVerificarAsesor);

        jVerificarTecnico.setBackground(new java.awt.Color(188, 202, 236));
        jVerificarTecnico.setText("Verificar Tecnico");
        jVerificarTecnico.setOpaque(true);
        jVerificarTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVerificarTecnicoActionPerformed(evt);
            }
        });
        jMenu1.add(jVerificarTecnico);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(101, 132, 255));
        jMenu2.setText("Consultar");
        jMenu2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jMenu2.setOpaque(true);
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenu13.setBackground(new java.awt.Color(188, 202, 236));
        jMenu13.setText("Disponibilidad");
        jMenu13.setOpaque(true);

        jMenuItem1.setBackground(new java.awt.Color(188, 202, 236));
        jMenuItem1.setText("Disponibilidad SI");
        jMenuItem1.setOpaque(true);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem1);

        jMenuItem7.setBackground(new java.awt.Color(188, 202, 236));
        jMenuItem7.setText("Disponibilidad NO");
        jMenuItem7.setOpaque(true);
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem7);

        jMenu2.add(jMenu13);

        jMenu14.setBackground(new java.awt.Color(188, 202, 236));
        jMenu14.setText("Verificar Estado de Averia");
        jMenu14.setOpaque(true);

        jMenuItem8.setBackground(new java.awt.Color(188, 202, 236));
        jMenuItem8.setText("En proceso");
        jMenuItem8.setOpaque(true);
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem8);

        jMenuItem6.setBackground(new java.awt.Color(188, 202, 236));
        jMenuItem6.setText("No atendido");
        jMenuItem6.setOpaque(true);
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem6);

        jMenuItem9.setBackground(new java.awt.Color(188, 202, 236));
        jMenuItem9.setText("Finalizado");
        jMenuItem9.setOpaque(true);
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem9);

        jMenu2.add(jMenu14);

        jMenu15.setBackground(new java.awt.Color(188, 202, 236));
        jMenu15.setText("Verificar Averia según ubicación");
        jMenu15.setOpaque(true);

        jMenuItem10.setBackground(new java.awt.Color(188, 202, 236));
        jMenuItem10.setText("Pendiente Si");
        jMenuItem10.setOpaque(true);
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem10);

        jMenuItem3.setBackground(new java.awt.Color(188, 202, 236));
        jMenuItem3.setText("Pendiente No");
        jMenuItem3.setOpaque(true);
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem3);

        jMenu2.add(jMenu15);

        jMenuBar1.add(jMenu2);

        jMenu12.setBackground(new java.awt.Color(101, 132, 255));
        jMenu12.setText("Ayuda");
        jMenu12.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        jMenu12.setOpaque(true);

        jMenuInfoSistema.setBackground(new java.awt.Color(188, 202, 236));
        jMenuInfoSistema.setText("Información del Sistema");
        jMenuInfoSistema.setOpaque(true);
        jMenuInfoSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInfoSistemaActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuInfoSistema);

        jMenuBar1.add(jMenu12);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuInfoSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInfoSistemaActionPerformed
        IUacercaD frmAcercaDe = new IUacercaD();
        frmAcercaDe.setVisible(true);
    }//GEN-LAST:event_jMenuInfoSistemaActionPerformed

    private void jMenuVerificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVerificarUsuarioActionPerformed
        RegistroUsuarioIU frmRegistroUsuario = new RegistroUsuarioIU();
        frmRegistroUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuVerificarUsuarioActionPerformed

    private void jVerificarAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVerificarAsesorActionPerformed
        // TODO add your handling code here:
        RegistroAsesorIU frmRegistroAsesor = new RegistroAsesorIU();
        frmRegistroAsesor.setVisible(true);
    }//GEN-LAST:event_jVerificarAsesorActionPerformed

    private void jVerificarTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVerificarTecnicoActionPerformed
        RegistroTecnicoIU frmRegistroTecnico = new RegistroTecnicoIU();
        frmRegistroTecnico.setVisible(true);
    }//GEN-LAST:event_jVerificarTecnicoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        IUAgendar frmAgendar = new IUAgendar();
        frmAgendar.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        IUAgendar2 frmAgendar = new IUAgendar2();
        frmAgendar.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        IUConsulta2a frmConsulta = new IUConsulta2a();
        frmConsulta.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        IUConsulta2b frmConsulta = new IUConsulta2b();
        frmConsulta.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        IUConsulta2c frmConsulta = new IUConsulta2c();
        frmConsulta.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        IUConsulta3a frmConsulta= new IUConsulta3a();
        frmConsulta.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        IUConsulta3b frmConsulta= new IUConsulta3b();
        frmConsulta.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IUPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuItem jMenuInfoSistema;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuVerificarUsuario;
    private javax.swing.JMenuItem jVerificarAsesor;
    private javax.swing.JMenuItem jVerificarTecnico;
    // End of variables declaration//GEN-END:variables
}
