/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import javax.swing.table.DefaultTableModel;
import control.*;
import Modelo.*;
import Datos.*;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Alexander Cruz
 */
public class RegistroTecnicoIU extends javax.swing.JFrame {
    ArrayList<Tecnico>Tecnico;
    GestorTecnico db = new GestorTecnico();
    
    private GestorTecnico gestorTecnico;
    private DefaultTableModel modeloTablaTecnico;

    
    public RegistroTecnicoIU(GestorTecnico gestorTecnico) {
        initComponents();
        
        this.gestorTecnico = gestorTecnico;
        
        modeloTablaTecnico = new DefaultTableModel();
        modeloTablaTecnico.addColumn("DNI_Tecnico");
        modeloTablaTecnico.addColumn("Nombre");
        modeloTablaTecnico.addColumn("Celular");
        modeloTablaTecnico.addColumn("Compañia");
        modeloTablaTecnico.addColumn("Especializacion");
        
        tablaTecnico.setModel(modeloTablaTecnico);
        actualizarTablaTecnico();
    }
    public void ListarDatos(){
        Tecnico = db.ListTecnicos();
        DefaultTableModel tb = (DefaultTableModel)tablaTecnico.getModel();
        for (Tecnico user: Tecnico ) {
            tb.addRow(new Object[]{user.getDNI_TECNICO(),user.getNombreTecnico(),user.getCelTecnico(),user.getCompañia(),user.getEspecialización()});
        }
    }
    public void LimpiarFormulario(){
        DefaultTableModel tb = (DefaultTableModel)tablaTecnico.getModel();
        for (int i = tb.getRowCount()-1; i>=0; i--) {
            tb.removeRow(i);
        }
    }
    public void limpiarTablaTecnico() {
        for (int i = modeloTablaTecnico.getRowCount() - 1; i >= 0; i--) {
            modeloTablaTecnico.removeRow(i);
        }
    }
    public RegistroTecnicoIU(){
        initComponents();
        this.gestorTecnico = new GestorTecnico();
        modeloTablaTecnico = new DefaultTableModel();
        modeloTablaTecnico.addColumn("DNI_Tecnico");
        modeloTablaTecnico.addColumn("Nombre");
        modeloTablaTecnico.addColumn("Celular");
        modeloTablaTecnico.addColumn("Compañia");
        modeloTablaTecnico.addColumn("Especializacion");
        
        tablaTecnico.setModel(modeloTablaTecnico);
        actualizarTablaTecnico();
        
    }
    public void actualizarTablaTecnico(){
        limpiarTablaTecnico();
        for (int i = 0; i < gestorTecnico.longitud(); i++) {
            Tecnico tecnico = gestorTecnico.iesimo(i);
            String[] fila = new String [5];
            int DNI = tecnico.getDNI_TECNICO();
            int cel = tecnico.getCelTecnico();
            
            fila[0] = String.valueOf(DNI);
            fila[1] = tecnico.getNombreTecnico();
            fila[2] = String.valueOf(cel);
            fila[3] = tecnico.getCompañia();
            fila[4] = tecnico.getEspecialización();
            
            modeloTablaTecnico.addRow(fila);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtDniTecnico = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombreTec = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCompania = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEspecializacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTecnico = new javax.swing.JTable();
        btnRegistarTec = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtBuscarDni = new javax.swing.JTextField();
        txtCambiarCorreo = new javax.swing.JTextField();
        btnBorrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtCambiarCel = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCambiarEspe = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(961, 678));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("DNI del Tecnico");

        txtDniTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniTecnicoActionPerformed(evt);
            }
        });
        txtDniTecnico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDniTecnicoKeyReleased(evt);
            }
        });

        jLabel3.setText("Nombre");

        txtNombreTec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreTecKeyReleased(evt);
            }
        });

        jLabel4.setText("Celular");

        txtCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCelularKeyReleased(evt);
            }
        });

        jLabel5.setText("Compañia");

        txtCompania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompaniaActionPerformed(evt);
            }
        });
        txtCompania.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCompaniaKeyReleased(evt);
            }
        });

        jLabel6.setText("Especialización");

        txtEspecializacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspecializacionActionPerformed(evt);
            }
        });
        txtEspecializacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEspecializacionKeyReleased(evt);
            }
        });

        tablaTecnico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaTecnico);

        btnRegistarTec.setText("Registrar");
        btnRegistarTec.setEnabled(false);
        btnRegistarTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarTecActionPerformed(evt);
            }
        });

        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2 (1).png"))); // NOI18N
        btnListar.setText("Obtener");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actualizar (2).png"))); // NOI18N
        btnModificar.setText("Actualizar");
        btnModificar.setPreferredSize(new java.awt.Dimension(111, 33));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel8.setText("INGRESAR DNI Y CORREO PARA REEMPLAZAR");

        jLabel9.setText("BUSCAR DNI");

        jLabel10.setText("Actualizar Compañia");

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar.png"))); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        jLabel7.setText("Actualizar Celular");

        txtCambiarCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCambiarCelActionPerformed(evt);
            }
        });

        jLabel11.setText("Actualizar Especialización");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCambiarCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(txtCambiarEspe)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBuscarDni, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCambiarCel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtBuscarDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCambiarCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCambiarCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCambiarEspe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrar)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(7, 43, 255));
        jLabel1.setText("REGISTRAR TECNICO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDniTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreTec)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCompania)
                            .addComponent(txtEspecializacion, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnListar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistarTec, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtDniTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNombreTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCompania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtEspecializacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistarTec, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        super.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtEspecializacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecializacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecializacionActionPerformed

    private void txtDniTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniTecnicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniTecnicoActionPerformed

    private void txtCompaniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompaniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompaniaActionPerformed

    private void btnRegistarTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarTecActionPerformed
        // TODO add your handling code here:
        int DNI = Integer.valueOf(txtDniTecnico.getText());
        String Nombre = txtNombreTec.getText();
        int Cel = Integer.valueOf(txtCelular.getText());
        String compania = txtCompania.getText();
        String Especializacion = txtEspecializacion.getText();
        
        Tecnico objTecnico = new Tecnico (DNI,Nombre,Cel,compania,Especializacion);
        try {
            GestorTecnico.registrarTecnico(objTecnico);
            JOptionPane.showMessageDialog(rootPane, "Se agrego con Exito..");
            txtDniTecnico.setText("");
            txtNombreTec.setText("");
            txtCelular.setText("");
            txtCompania.setText("");
            txtEspecializacion.setText("");
            txtDniTecnico.requestFocus();
            txtCelular.requestFocus();
        } catch (Exception ex) {
            Logger.getLogger(RegistroUsuarioIU.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnRegistarTecActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        LimpiarFormulario();
        ListarDatos();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int DNI = Integer.valueOf(txtBuscarDni.getText());
        String compania = txtCambiarCorreo.getText();
        int cel = Integer.valueOf(txtCambiarCel.getText());
        String Especializacion = txtCambiarEspe.getText();
        try {
            GestorTecnico.actualizarDatos(compania, cel,Especializacion,DNI);
            JOptionPane.showMessageDialog(rootPane, "Se modifico con Exito..");
            txtBuscarDni.setText("");
            txtCambiarCorreo.setText("");
            txtCambiarCel.setText("");
            txtCambiarEspe.setText("");
        } catch (Exception ex) {
            Logger.getLogger(RegistroUsuarioIU.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        int DNI = Integer.valueOf(txtBuscarDni.getText());
        try {
            GestorTecnico.eliminarUsuario(DNI);
                JOptionPane.showMessageDialog(rootPane, "Se borro con Exito..");
                txtBuscarDni.setText(""); 
            
            
        } catch (Exception ex) {
            Logger.getLogger(RegistroUsuarioIU.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnBorrarActionPerformed
    public void HabilitarBoton(){
        
        if (!txtDniTecnico.getText().isEmpty()
                && !txtNombreTec.getText().isEmpty()
                && !txtCelular.getText().isEmpty()
                && !txtCompania.getText().isEmpty()
                && !txtEspecializacion.getText().isEmpty()
                ) {
            btnRegistarTec.setEnabled(true);
            
        }else{
            btnRegistarTec.setEnabled(false);
            }
        }
    private void txtCambiarCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCambiarCelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCambiarCelActionPerformed

    private void txtDniTecnicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniTecnicoKeyReleased
        // TODO add your handling code here:
        HabilitarBoton();
    }//GEN-LAST:event_txtDniTecnicoKeyReleased

    private void txtNombreTecKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreTecKeyReleased
        // TODO add your handling code here:
        HabilitarBoton();
    }//GEN-LAST:event_txtNombreTecKeyReleased

    private void txtCelularKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularKeyReleased
        // TODO add your handling code here:
        HabilitarBoton();
    }//GEN-LAST:event_txtCelularKeyReleased

    private void txtCompaniaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCompaniaKeyReleased
        // TODO add your handling code here:
        HabilitarBoton();
    }//GEN-LAST:event_txtCompaniaKeyReleased

    private void txtEspecializacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEspecializacionKeyReleased
        // TODO add your handling code here:
        HabilitarBoton();
    }//GEN-LAST:event_txtEspecializacionKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroTecnicoIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroTecnicoIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroTecnicoIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroTecnicoIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroTecnicoIU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistarTec;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaTecnico;
    private javax.swing.JTextField txtBuscarDni;
    private javax.swing.JTextField txtCambiarCel;
    private javax.swing.JTextField txtCambiarCorreo;
    private javax.swing.JTextField txtCambiarEspe;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCompania;
    private javax.swing.JTextField txtDniTecnico;
    private javax.swing.JTextField txtEspecializacion;
    private javax.swing.JTextField txtNombreTec;
    // End of variables declaration//GEN-END:variables
}
